spring:
#  lifecycle:
#    timeout-per-shutdown-phase: 30s
#  main:
#    allow-circular-references: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  cache:
#    jcache:
#      config: classpath:ehcache.xml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:parking_management}
    username: ${DB_USER:parking_management}
    password: ${DB_PASSWORD:parking_management}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 580000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
  flyway:
    baseline-on-migrate: true
    enabled: ${FLYWAY_ENABLED:true}